openapi: 3.0.0
info:
  title: Key-Value Store API
  description: A simple key-value store API to manage data.
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /{key}:
    get:
      summary: Get a value by key
      parameters:
        - name: key
          in: path
          required: true
          description: The key of the value to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Successful retrieval of the value
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: string
        '404':
          description: Key not found
    put:
      summary: Store a value by key
      parameters:
        - name: key
          in: path
          required: true
          description: The key to store the value under
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
      responses:
        '202':
          description: Value accepted for storage
        '400':
          description: Invalid request body
        '500':
          description: Unable to store value
    delete:
      summary: Delete a value by key
      parameters:
        - name: key
          in: path
          required: true
          description: The key of the value to delete
          schema:
            type: string
      responses:
        '200':
          description: Value successfully deleted
        '404':
          description: Key not found
  /:
    get:
      summary: List all keys
      responses:
        '200':
          description: Successful retrieval of all keys
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
